### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [3]:
np.random.rand(2, 3) # 2행 3열 랜덤 행렬 생성

array([[0.84086799, 0.30002925, 0.70686057],
       [0.87680231, 0.57179413, 0.6610447 ]])

In [5]:
np.random.rand(10) # 1차원 행렬

array([0.80292142, 0.34756183, 0.48783733, 0.86316509, 0.24437337,
       0.24335822, 0.71842573, 0.03939438, 0.19914124, 0.21454696])

In [7]:
np.random.rand(4, 5, 3) # 5행 3열 행렬 4개 생성

array([[[0.84246398, 0.73805253, 0.34576843],
        [0.73891833, 0.34604166, 0.0929467 ],
        [0.17872659, 0.23766017, 0.30783857],
        [0.81207603, 0.06807401, 0.77810932],
        [0.79949217, 0.27245734, 0.0423747 ]],

       [[0.24262146, 0.38273884, 0.82311793],
        [0.46241444, 0.56671885, 0.2378066 ],
        [0.65522584, 0.79856371, 0.44831681],
        [0.91528722, 0.74071836, 0.49109096],
        [0.13384861, 0.78923075, 0.16673369]],

       [[0.44960063, 0.72986825, 0.75777242],
        [0.17191072, 0.80112073, 0.47633567],
        [0.31078568, 0.28357888, 0.70620144],
        [0.06373146, 0.89553169, 0.91833946],
        [0.47193036, 0.18923761, 0.48347688]],

       [[0.59004033, 0.60648677, 0.55964914],
        [0.06959845, 0.90748796, 0.03461995],
        [0.5085695 , 0.32786768, 0.72610572],
        [0.48364739, 0.0730066 , 0.2433144 ],
        [0.70332782, 0.72967214, 0.12640999]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [8]:
np.random.randn(3, 4) # 정규분포애서 샘플링해서 생성

array([[-0.75765761, -0.22494284, -0.43855932, -1.31504908],
       [-0.3084368 , -1.24850303, -0.42495614,  0.44004569],
       [ 1.5069541 ,  0.6875555 ,  0.22897132,  0.52015909]])

In [10]:
np.random.randn(3, 4, 2)

array([[[-0.12431434,  0.57353567],
        [-0.00956728, -0.70842016],
        [-0.9949641 ,  0.12251131],
        [ 0.10806653, -0.48089986]],

       [[-1.5112801 ,  0.01054174],
        [ 1.28769367, -0.25759641],
        [-0.22958966,  0.63992798],
        [ 0.01642098,  1.39808577]],

       [[-1.78730429,  0.47337087],
        [-0.95581493, -0.62536579],
        [ 0.38685118, -1.15307761],
        [-0.53942456, -1.4839747 ]]])

In [12]:
np.random.randn(5) # 벡터로 정규분포형태 값 출력

array([ 1.13199949,  0.39775995,  0.1761283 ,  0.87793409, -0.40451829])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [14]:
np.random.randint(1, 100, size = (3, 5)) # 3행 5열으로 1부터 100 사이에서 랜덤하게  sampling

array([[58, 82, 44, 79, 58],
       [35,  5, 33, 22, 37],
       [30, 25, 96, 54, 91]])

In [43]:
np.random.randint(1, 100, size = (5, ))

array([77,  4, 71,  4, 85])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [50]:
np.random.seed(100)

In [52]:
np.random.randn(3, 4) # 랜덤한 값을 동일한 값으로 다시 출력시킴

array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [56]:
np.random.choice(100, size = (3, 4)) # 100안에서 3행 4열로 샘플링

array([[57, 76,  3, 70],
       [ 3, 84, 79, 10],
       [87, 60,  3, 48]])

In [53]:
np.random.choice(100, (3, 4))

array([[39, 38, 44, 18],
       [64, 56, 34, 53],
       [74, 17, 72, 13]])

In [57]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size = (2, 2), replace = False) # replace = False 는 중복을 허용 x

array([[4.9, 3. ],
       [2. , 1. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [62]:
np.random.uniform(1.0, 3.0, size = (4, 5)) # uniform한 분포해서 랜덤하게 샘플링 1.0과 3.0 사이에서 4행 5열로

array([[2.22065631, 1.6180007 , 2.39546982, 2.71923659, 2.25064752],
       [2.96481566, 2.95300025, 1.33338826, 1.04635627, 1.3214891 ],
       [2.84699365, 2.9070997 , 1.42195684, 1.7210505 , 2.09875052],
       [1.5436617 , 1.92120324, 2.39232313, 2.00071179, 2.43214198]])

In [61]:
np.random.normal(size = (3, 4)) # np.random.randn(3, 4) 와 같음

array([[-1.8411883 ,  0.36609323, -0.33177714, -0.68921798],
       [ 2.03460756, -0.55071441,  0.75045333, -1.30699234],
       [ 0.58057334, -1.10452309,  0.69012147,  0.68689007]])