## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [4]:
x = np.random.rand(3, 3) # 정방행렬이어야함
print(x)

x @ np.linalg.inv(x) # 행렬의 곱은 @ 사용하기
np.matmul(x, np.linalg.inv(x)) # 또는 이렇게 써도 됨

[[2.17584205e-01 2.66386546e-04 5.22403514e-01]
 [6.35113704e-01 6.00705404e-01 1.81482199e-01]
 [3.73868033e-01 6.14189310e-01 7.49993030e-01]]


array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [-2.77555756e-16,  1.00000000e+00,  1.11022302e-16],
       [-1.11022302e-16, -1.11022302e-16,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [11]:
A = np.array([[1, 1], [2 ,4]])
B = np.array([25, 64])

print(A)
print(B)

x = np.linalg.solve(A, B)
print(x) # x가 18, y가 7 임을 구할 수 있음.

np.allclose(A@x, B) # 답확인 하기

[[1 1]
 [2 4]]
[25 64]
[18.  7.]


True