## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

##### ndarray 기본 함수 사용하기

In [4]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.70876062 0.48247014 0.44045632 0.74462647 0.03941276]
 [0.66903968 0.82996845 0.95353055 0.69881375 0.26190931]
 [0.90460182 0.93142067 0.21977788 0.04998444 0.2503864 ]]


#### 연산 함수
 - add, substract, multiply, divide

In [5]:
np.add(x, y)

array([[ 0.70876062,  1.48247014,  2.44045632,  3.74462647,  4.03941276],
       [ 5.66903968,  6.82996845,  7.95353055,  8.69881375,  9.26190931],
       [10.90460182, 11.93142067, 12.21977788, 13.04998444, 14.2503864 ]])

In [6]:
x + y

array([[ 0.70876062,  1.48247014,  2.44045632,  3.74462647,  4.03941276],
       [ 5.66903968,  6.82996845,  7.95353055,  8.69881375,  9.26190931],
       [10.90460182, 11.93142067, 12.21977788, 13.04998444, 14.2503864 ]])

In [7]:
x - y

array([[-0.70876062,  0.51752986,  1.55954368,  2.25537353,  3.96058724],
       [ 4.33096032,  5.17003155,  6.04646945,  7.30118625,  8.73809069],
       [ 9.09539818, 10.06857933, 11.78022212, 12.95001556, 13.7496136 ]])

In [8]:
x / y

array([[  0.        ,   2.07266713,   4.54074535,   4.02886567,
        101.48998498],
       [  7.47339833,   7.22919049,   7.34113865,  11.44797172,
         34.3630396 ],
       [ 11.05458755,  11.8099161 ,  54.6005812 , 260.08095354,
         55.91357975]])

In [9]:
x * y

array([[ 0.        ,  0.48247014,  0.88091264,  2.2338794 ,  0.15765102],
       [ 3.34519838,  4.97981068,  6.67471387,  5.59050997,  2.35718379],
       [ 9.04601818, 10.24562741,  2.63733456,  0.64979768,  3.50540961]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [10]:
print(y)

[[0.70876062 0.48247014 0.44045632 0.74462647 0.03941276]
 [0.66903968 0.82996845 0.95353055 0.69881375 0.26190931]
 [0.90460182 0.93142067 0.21977788 0.04998444 0.2503864 ]]


In [11]:
np.mean(y)

0.5456772832377049

In [12]:
y.mean()

0.5456772832377049

In [13]:
np.max(y)

0.9535305528336369

In [14]:
y.max()

0.9535305528336369

In [16]:
np.argmax(y) # 행렬을 flatting 한 상태로 가장 높은 index를 가져온다.

7

In [18]:
np.var(y), np.median(y), np.std(y) # var : 분산, median : 중앙값, std : 표준편차

(0.0947099800193005, 0.6690396767044076, 0.30774986599396026)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [19]:
y

array([[0.70876062, 0.48247014, 0.44045632, 0.74462647, 0.03941276],
       [0.66903968, 0.82996845, 0.95353055, 0.69881375, 0.26190931],
       [0.90460182, 0.93142067, 0.21977788, 0.04998444, 0.2503864 ]])

In [23]:
np.cumsum(y) # n과 n+1의 자리의 합의 값

array([0.70876062, 1.19123076, 1.63168709, 2.37631355, 2.41572631,
       3.08476598, 3.91473443, 4.86826498, 5.56707873, 5.82898804,
       6.73358986, 7.66501053, 7.88478841, 7.93477285, 8.18515925])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [24]:
np.std(np.arange(1, 5))

1.118033988749895

In [25]:
z = np.random.randn(10)
print(z)

[ 1.06466025 -0.22205735 -0.48215257  1.62097341  1.09866975 -1.13792663
  1.15875861  0.44621962 -0.21523472  3.30327938]


In [28]:
z > 0

array([ True, False, False,  True,  True, False,  True,  True, False,
        True])

In [26]:
np.any(z > 0)

True

In [29]:
np.all( z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [30]:
z = np.random.randn(10)
print(z)

[ 0.33585206 -0.22610747  0.42229874 -0.29406688  1.19037143  0.42139252
  0.4498404   1.07304358 -0.71729473  0.00185847]


In [31]:
np.where(z > 0, z, 0) # 조건: z > 0 이면 만약 True이면 z 출력, False 이면 0 출력 하라.

array([0.33585206, 0.        , 0.42229874, 0.        , 1.19037143,
       0.42139252, 0.4498404 , 1.07304358, 0.        , 0.00185847])