### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [8]:
x = np.array([1, 2, 3, 4]) # 1차원 벡터
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]]) # 2차원 벡터
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [14]:
np.ones((4, 5)) # 4행 5열에 1만 갖는 함수

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((2, 3, 4)) # 3행 4열 행렬 2개

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
np.zeros((3, 3, 8, 8)) # 0으로 만들어진 4차원

array([[[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
       

#### np.empty, np.full로 생성하기

In [20]:
np.empty((3, 4)) # 3행 4열로 초기화

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.full((3, 4), 7) # 3행 4열로 7로 채움

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [24]:
np.eye(3) # 항등 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### np.linspace로 생성하기

In [26]:
np.linspace(1, 10, 3) # 1(처음)에서 끝(10)까지 3등분으로 동일하게 간격 구성

array([ 1. ,  5.5, 10. ])

In [29]:
np.linspace(1, 10, 4) # 1에서부터 10까지 4등분을 동일한 간격으로

array([ 1.,  4.,  7., 10.])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [34]:
x = np.arange(1, 16)
print(x)

x.shape

x.reshape(3, 5) # 3행 5열로 벡터 -> 행렬로 변환

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])