## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [2]:
import numpy as np

In [3]:
x = np.random.randint(1, 100, size = 10)

In [4]:
x

array([73, 49,  6, 11, 32,  7, 39, 34, 10, 19])

In [5]:
even_mask = (x % 2 == 0) # 1 차원이기 때문에 브로드캐스팅이 됨
print(even_mask)

[False False  True False  True False False  True  True False]


- bool 리스트를 인덱스로 전달

In [7]:
x[even_mask] # True 인 것만 filltering 하여 불러옴

array([ 6, 32, 34, 10])

In [8]:
x[x%2 == 0]

array([ 6, 32, 34, 10])

In [9]:
x[x > 30]

array([73, 49, 32, 39, 34])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [12]:
x[(x%2 == 0) & (x < 30)]

array([ 6, 10])

In [13]:
x[(x<30) | (x > 50)]

array([73,  6, 11,  7, 10, 19])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [14]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [15]:
temp_25 = temp > 25
print(temp_25)

[False False False  True  True  True  True  True False False False False
 False  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]


In [21]:
len(temp[temp_25]) # 25도를 넘는 날의 수

21

In [20]:
np.mean(temp[temp_25]) # 평균기온

26.857142857142858

In [22]:
temp = np.random.randint(22, 28, size = 31)

In [23]:
np.mean(temp[temp > 25])

26.555555555555557

In [25]:
len(temp[temp>25])

9